//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input Settings/Pruebas.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Pruebas: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Pruebas()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Pruebas"",
    ""maps"": [
        {
            ""name"": ""PantallaTactil"",
            ""id"": ""c7b100e9-33e7-4b0b-b618-72786da7d504"",
            ""actions"": [
                {
                    ""name"": ""LaRotacion"",
                    ""type"": ""Button"",
                    ""id"": ""d9733841-e10c-46fe-8fb2-c0384a54b3b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5370377a-b9fb-41c8-900b-56c58edd6811"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaRotacion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PantallaTactil
        m_PantallaTactil = asset.FindActionMap("PantallaTactil", throwIfNotFound: true);
        m_PantallaTactil_LaRotacion = m_PantallaTactil.FindAction("LaRotacion", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PantallaTactil
    private readonly InputActionMap m_PantallaTactil;
    private List<IPantallaTactilActions> m_PantallaTactilActionsCallbackInterfaces = new List<IPantallaTactilActions>();
    private readonly InputAction m_PantallaTactil_LaRotacion;
    public struct PantallaTactilActions
    {
        private @Pruebas m_Wrapper;
        public PantallaTactilActions(@Pruebas wrapper) { m_Wrapper = wrapper; }
        public InputAction @LaRotacion => m_Wrapper.m_PantallaTactil_LaRotacion;
        public InputActionMap Get() { return m_Wrapper.m_PantallaTactil; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PantallaTactilActions set) { return set.Get(); }
        public void AddCallbacks(IPantallaTactilActions instance)
        {
            if (instance == null || m_Wrapper.m_PantallaTactilActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PantallaTactilActionsCallbackInterfaces.Add(instance);
            @LaRotacion.started += instance.OnLaRotacion;
            @LaRotacion.performed += instance.OnLaRotacion;
            @LaRotacion.canceled += instance.OnLaRotacion;
        }

        private void UnregisterCallbacks(IPantallaTactilActions instance)
        {
            @LaRotacion.started -= instance.OnLaRotacion;
            @LaRotacion.performed -= instance.OnLaRotacion;
            @LaRotacion.canceled -= instance.OnLaRotacion;
        }

        public void RemoveCallbacks(IPantallaTactilActions instance)
        {
            if (m_Wrapper.m_PantallaTactilActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPantallaTactilActions instance)
        {
            foreach (var item in m_Wrapper.m_PantallaTactilActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PantallaTactilActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PantallaTactilActions @PantallaTactil => new PantallaTactilActions(this);
    public interface IPantallaTactilActions
    {
        void OnLaRotacion(InputAction.CallbackContext context);
    }
}
